### ISSUE TITLE
When attempting to delete an entry, the following error occurs on SaveChange()

### ISSUE THREAD

**Issue by Connorapple** [productivityinterns/productivitywebapp#12]
`Exception has occurred: CLR/Microsoft.EntityFrameworkCore.DbUpdateException
An exception of type 'Microsoft.EntityFrameworkCore.DbUpdateException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'An error occurred while updating the entries. See the inner exception for details.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Microsoft.Data.Sqlite.SqliteException : SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)`

**Comment by S4lt5** [comment]
You have a child that points to a parent that doesn't exist. Check to make
sure you didn't accidentally change an Id or something?

**Comment by Connorapple** [comment]
So I don't know how this would be accessing a non-existent parent, or even if this would actually save, having a bit of trouble getting a feel for the way DbSet handles data:
 ```
public void SaveFlow(Flow flow)
        {
            //TODO: Save something here!
            Flows.Add(flow);
            SaveChanges();

        }
```
